[language-server.lsp-ai]
command = "lsp-ai"

[language-server.lsp-ai.config.memory]
file_store = {}

[language-server.lsp-ai.config.models.gpt4o]
type = "open_ai"
chat_endpoint = "https://api.openai.com/v1/chat/completions"
model = "gpt-4o"
auth_token_env_var_name = "OPENAI_API_KEY"

[[language-server.lsp-ai.config.chat]]
trigger = "!C"
action_display_name = "Chat"
model = "gpt4o"
parameters = {max_context = 4096, max_tokens = 1024, messages = [{ role = "system", content = "You are a helpful programming assistant. The user will ask you for assistance coding and you will do you best to answer succinctly and accurately"}]}

[[language-server.lsp-ai.config.chat]]
trigger = "!CC"
action_display_name = "Chat with context"
model = "gpt4o"
parameters = {max_context = 4096, max_tokens = 1024, messages = [{ role = "system", content = "You are a code assistant chatbot. The user will ask you for assistance coding and you will do you best to answer succinctly and accurately given the code context:\n\n{CONTEXT}"}]}

# [language-server.lsp-ai.config.completion]
# model = "gpt4o"
# parameters = {max_context = 4096, max_tokens = 1024, messages = [{ role = "system", content = "You are a helpful programming assitant providing in-editor autocomplete functionality. The user will provide a code fragment or snippet, do your best to provide the code the user wants. Use a terse code style with minimal comments. Make sure to provide complete implementations, do not leave anything as an exercise to the user."}, {role = "user", content = "{CONTEXT} and {CODE}"}]}

[[language-server.lsp-ai.actions]]
action_display_name = "Complete"
model = "gpt4o"
parameters = { max_context = 4096, max_tokens = 4096, messages = [{role = "system", content = "You are an AI coding assistant. Your task is to complete code snippets. The user's cursor position is marked by \"<CURSOR>\". Follow these steps:\n\n1. Analyze the code context and the cursor position.\n2. Provide your chain of thought reasoning, wrapped in <reasoning> tags. Include thoughts about the cursor position, what needs to be completed, and any necessary formatting.\n3. Determine the appropriate code to complete the current thought, including finishing partial words or lines.\n4. Replace \"<CURSOR>\" with the necessary code, ensuring proper formatting and line breaks.\n5. Wrap your code solution in <answer> tags. Do not wrap your solution in backticks '`', use only <answer> tags.\n\nYour response should always include both the reasoning and the answer. Pay special attention to completing partial words or lines before adding new lines of code.\n\n<examples>\n<example>\nUser input:\n--main.py--\n# A function that reads in user inpu<CURSOR>\n\nResponse:\n<reasoning>\n1. The cursor is positioned after \"inpu\" in a comment describing a function that reads user input.\n2. We need to complete the word \"input\" in the comment first.\n3. After completing the comment, we should add a new line before defining the function.\n4. The function should use Python's built-in `input()` function to read user input.\n5. We'll name the function descriptively and include a return statement.\n</reasoning>\n\n<answer>t\ndef read_user_input():\n    user_input = input(\"Enter your input: \")\n    return user_input\n</answer>\n</example>\n\n<example>\nUser input:\n--main.py--\ndef fibonacci(n):\n    if n <= 1:\n        return n\n    else:\n        re<CURSOR>\n\n\nResponse:\n<reasoning>\n1. The cursor is positioned after \"re\" in the 'else' clause of a recursive Fibonacci function.\n2. We need to complete the return statement for the recursive case.\n3. The \"re\" already present likely stands for \"return\", so we'll continue from there.\n4. The Fibonacci sequence is the sum of the two preceding numbers.\n5. We should return the sum of fibonacci(n-1) and fibonacci(n-2).\n</reasoning>\n\n<answer>turn fibonacci(n-1) + fibonacci(n-2)</answer>\n</example>\n</examples>"}, {role = "user", content = "{CODE}"} ]}
post_process = {extractor = "(?s)<answer>(.*?)</answer>"}

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.pyright.config.analysis]
autoSearchPaths = true
diagnosticMode = "workspace"
useLibraryCodeForTypes = true
reportMissingImports = true
disableTaggedHints = true
typeCheckingMode = "basic"

[language-server.pylsp.config.plugins]
pycodestyle = {enabled = false, maxLineLength = 88}
flake8 = {enabled = false, ignore = ["E501"], maxLineLength = 88}
pyflakes = {enabled = false}
pylint = {enabled = false}
autopep8 = {enabled = false}
mccabe = {enabled = false}

[language-server.ruff-lsp]
command = "ruff-lsp"

[[language]]
name = "python"
scope = "source.python"
file-types = ["py", "pyi"]
shebangs = ["python"]
comment-token = "#"
roots = ["pyproject.toml"]
language-servers = ["pyright", "ruff-lsp", "lsp-ai"]
# formatter = { command = "black", args = ["--quiet", "--target-version", "py312", "-"] }
formatter = { command = "ruff", args = ["format", "--quiet", "--target-version", "py312", "-"] }
auto-format = true

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }
